# fly.toml app configuration file generated for blox-frontend on 2024-09-03T09:40:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blox-frontend'
primary_region = 'ams'
swap_size_mb = 512

[build]

[http_service]
internal_port = 8043
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
